baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[params]
  subtitle = "Adventures in Hugoland"
  copyright = "Copyright © 2018"
  author = "Pointy Far"

  footerNotice = "Powered by Hugo. Themed by PointyFar"

  brand = "Pointy's"

