baseURL = "https://pfht.netlify.com/"
languageCode = "en-us"
title = "PointyFar's Filterable Hugo Themes"

[params]
  copyright = "Copyright © 2018"
  author = "Pointy Far"

  footerNotice = "Powered by Hugo. Themed by PointyFar"

  brand = "PFHT"
  
  version = "0.4.1"
  
[[params.social]]
  url = "https://github.com/pointyfar/"
  icon = "fab fa-github"

