baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Themes Filter"

[params]
  copyright = "Copyright © 2018"
  author = "Pointy Far"

  footerNotice = "Powered by Hugo. Themed by PointyFar"

  brand = "Pointy's"
  
[[params.social]]
  url = "https://github.com/pointyfar/"
  icon = "fab fa-github"

